"""默认配置值。"""

# 已知的字母前缀白名单。新增时直接往字符串里加词即可（用空格分隔）。
DEFAULT_PREFIXES = """
ABP ADN AKHO AQUCO ARA ARM ARMD ARMM AVOP AVOPVR BBTU BCDP BGG BOBB BRK
CAWD CJOB CJOD CKK CLT CMA CMF COFD CRC CSCT CWPBD DANDY DASD DDT DLDSS
DPMI DPMX DSVR DVAJ DVDES DVDMS DWD DWI EBOD EKDV ABS FAVKH FAX FCDSS
FSET GACHIP GAS GMEN GOPJ GUN HEYZO HIKR HJMO HMGL HMM HND HONB HTMS HUNT
HUNTA IENE IPX IPZZ JAC JUFE JUL JUQ JUR JUX JUY JYMA KAWD KBI KING KNB
KSBJ KYW LAFBD LUXU MAD MADM MAQQH MCB3DBD MCS MDBK MEKO MESS MEYD MIAA
MIAD MIDE MIDV MIGD MIMK MIRD MIST MIZD MKBD MKCK MKD MVSD MXGS NATR NCYF
NDS NEO NHDB NHDTA NHDTB NHDTC NITR NNPJ NSPS NYB OBA OFJE OHO OKSN OOMN
ORECS PGD PGFS PPBD PPPD PSI PTS RBD RCT RCTD RED RKI RMER SAMA SAME SCNN
SCOP SDAM SDDE SDMF SDMM SDMS SDMT SDMU SDNM SDNT SERO SHKD SIM SIRO SIVR
SKMJ SKYHD SMBD SMD SNIS SOE SONE SPRD SRS SSIS SSNI STAR STARS START SUPD
SVDVD SVVRT SYK TEN TMVI TUE TWYB TYWD UMSO URE USAG VAGU VDD VENU VENX VOD
WAAA MISM WANZ WBW WCX YMDD NWF DDB SDJS CRPD CLUB MDYD BOMN CBTB CLDG CVDX
DDOB DMDG DVUMA EMBZ EYAN KTKY MMB OPKT JUFD MUM NIRC OPUD REAL SMS VICD
DOKS WBMS YSN BYO DVMM SVNNP URAM SABA OKAD BIST BLK TEAM HODV IPZ TYOD GNE
MILD MXBD TPPN MKMP SDSI BEB DFE IPTD WNZ AGAV ANND DDHZ GSFV MEEL NTRD WSE
BIJN OKAX VERO AUKS CMV MVG GOJU GBL LZWM GACHI NAKA NDRA RANY SHN SON XRW
XVSR YST VEC ABW NNNC PKPD JUVR AJVR PRVR PRVRSS MDVR CJVR COSVR EXVR FCVR
KAVR KIWVR MAXVR TMAVR URVRSP VRPRD VRVR IPVR SAMPLE MIAE AKA AVGP BBAN SMA
ZEAA NHVR DANDYHQVR HUNVR OYCVR SAVR VRKM WAVR PPVR DMC ZOMD DSAM MIDA GOUL
HALE NIMA PAKO SYKH HMDNV IESP MLP IESM HAR GOIN DRPT GTJ MAAN MIFD HKHS HIKB
SHIC SIMM OPCYN IMGN MGFX DMTP ANB BDA BHG BRTM DNJR FONE GASS GEKI LUNS GVH
HAWA MFCS HMN KTKC NKHB OPBD HONE IDRK JMX DHT MILK MILF MMGH NINE NSSTH SKY
NTK BBA SEMM NASS PPP GANA AMTR HMDN INSTV FAN ACY AOZ ATID GONE DLPN DOCP
DOGD FERA BEAF BANK OCH OPPW SRH TOEN XMOM HTM IORA JJCC JRZE KPB KTKZ KUM
LADY MMND NACR PAI PARATHD SUN TIKP URKK VEO VRTM YTR FINH YRMN CADV KAKU
EKO TMHK AFS BMJO CETD DIY EVIS GENT GRMT HERY JKNK JRZD KDKJ TMHP UMD VGD
YAG PCTG MOT NSSTL ONSG PMGG HHED CHRV HNDB RDT BSK PRED RHJ SDGN ALOG NAMH
PIYO PKYS ABBA BNSPS CMN MANP REBN DYNS APOL CORE CWM LOL PNME CMC OAE IDBD
OME DASS FCT FSDSS FWAY HYPN JUTA KMHRS LAS MBRBN MSFH SENN SNOS TEK OSH UPSM
BKC COA CUS KNMB SKJK JKW JUSD KWSM SORA TGAV VGQ GIRO NAMHVR GHKO EMP MCDV
CESD OFES JKBX JUNY MKB PPSD URPW MTALL PFES JURA LULU RHN
""".split()


DEFAULT_EXTENSIONS = [
    # 视频
    ".mp4", ".avi", ".mkv", ".wmv", ".mov", ".flv", ".webm", ".rmvb",
    ".m4v", ".3gp", ".ts", ".mts", ".m2ts", ".vob", ".mpg", ".m3u8",
    # 镜像 / 字幕
    ".iso", ".img", ".srt", ".ass",
]